-- MySQL Script generated by MySQL Workbench
-- Thu Sep 19 08:58:42 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BoteroDb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sql10732878` ;

-- -----------------------------------------------------
-- Schema BoteroDb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sql10732878` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Table `BoteroDb`.`HistoricalContext`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql10732878`.`historical_context` (
  `id_historical_context` INT AUTO_INCREMENT NOT NULL ,
  `context_name` VARCHAR(250) NOT NULL,
  `description_context` TEXT(2000) NOT NULL,
  PRIMARY KEY (`id_historical_context`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BoteroDb`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql10732878`.`person` (
  `id_person` INT AUTO_INCREMENT NOT NULL,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_person`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `phone_UNIQUE` ON `sql10732878`.`person` (`phone` ASC);

CREATE UNIQUE INDEX `email_UNIQUE` ON `sql10732878`.`person` (`email` ASC);


-- -----------------------------------------------------
-- Table `BoteroDb`.`restoration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql10732878`.`restoration` (
  `id_restoration` INT AUTO_INCREMENT NOT NULL,
  `id_person` INT NOT NULL,
  `start_date_restoration` DATE NOT NULL,
  `end_date_restoration` DATE NOT NULL,
  `restoration_reason` TEXT(2000) NOT NULL,
  `budget` FLOAT NOT NULL,
  PRIMARY KEY (`id_restoration`),
  CONSTRAINT `fk_rest_person`
    FOREIGN KEY (`id_person`)
    REFERENCES `sql10732878`.`person` (`id_person`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_rest_person_idx` ON `sql10732878`.`restoration` (`id_person` ASC);


-- -----------------------------------------------------
-- Table `BoteroDb`.`technique`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql10732878`.`technique` (
  `id_technique` INT AUTO_INCREMENT NOT NULL,
  `technique_name` VARCHAR(250) NOT NULL,
  `technique_description` TEXT(2000) NOT NULL,
  PRIMARY KEY (`id_technique`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BoteroDb`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql10732878`.`location` (
  `id_location` INT AUTO_INCREMENT NOT NULL,
  `country` VARCHAR(170) NOT NULL,
  `departament` VARCHAR(170) NOT NULL,
  `city` VARCHAR(170) NOT NULL,
  `latitude` DECIMAL(9,6) NOT NULL,
  `longitude` DECIMAL(9,6) NOT NULL,
  PRIMARY KEY (`id_location`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BoteroDb`.`Typeartwork`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql10732878`.`type_artwork` (
  `id_type_artwork` INT AUTO_INCREMENT NOT NULL,
  `type_artwork` VARCHAR(250) NOT NULL,
  `type_artwork_description` TEXT(1000) NOT NULL,
  PRIMARY KEY (`id_type_artwork`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BoteroDb`.`DevelopmentSurface`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql10732878`.`development_surface` (
  `id_development` INT NOT NULL AUTO_INCREMENT,
  `surface_name` VARCHAR(250) NOT NULL,
  `surface_description` TEXT(2000) NOT NULL,
  PRIMARY KEY (`id_development`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BoteroDb`.`artwork`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql10732878`.`artwork` (
  `id_artwork` INT AUTO_INCREMENT NOT NULL,
  `artwork_title` VARCHAR(250) NOT NULL,
  `date_creation` DATE NOT NULL,
  `description_artwork` TEXT(2000) NOT NULL,
  `state_artwork` ENUM ('Habilitada', 'Deshabilitada') DEFAULT 'Habilitada',
  `high` DECIMAL(4,3) NOT NULL,
  `width` DECIMAL(4,3) NOT NULL,
  `depth` DECIMAL(4,3) NOT NULL,
  `verified_artwork` BOOLEAN NOT NULL,
  `historical_context` INT NOT NULL,
  `restoration` INT NOT NULL,
  `technique` INT NOT NULL,
  `location` INT NOT NULL,
  `type_artwork` INT NOT NULL,
  `development_surface` INT NOT NULL,
  PRIMARY KEY (`id_artwork`),
  CONSTRAINT `fk_artwork_historical_context`
    FOREIGN KEY (`historical_context`)
    REFERENCES `sql10732878`.`historical_context` (`id_historical_context`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_artwork_restoration`
    FOREIGN KEY (`restoration`)
    REFERENCES `sql10732878`.`restoration` (`id_restoration`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_artwork_technique`
    FOREIGN KEY (`technique`)
    REFERENCES `sql10732878`.`technique` (`id_technique`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_artwork_location`
    FOREIGN KEY (`location`)
    REFERENCES `sql10732878`.`location` (`id_location`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_artwork_type_artwork`
    FOREIGN KEY (`type_artwork`)
    REFERENCES `sql10732878`.`type_artwork` (`id_type_artwork`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_artwork_developmentSurface`
    FOREIGN KEY (`development_surface`)
    REFERENCES `sql10732878`.`development_surface` (`id_development`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_artwork_historical_context_idx` ON `sql10732878`.`artwork` (`historical_context` ASC) ;

CREATE INDEX `fk_artwork_restoration_idx` ON `sql10732878`.`artwork` (`restoration` ASC) ;

CREATE INDEX `fk_artwork_technique_idx` ON `sql10732878`.`artwork` (`technique` ASC) ;

CREATE INDEX `fk_artwork_location_idx` ON `sql10732878`.`artwork` (`location` ASC) ;

CREATE INDEX `fk_artwork_type_artwork_idx` ON `sql10732878`.`artwork` (`type_artwork` ASC) ;

CREATE INDEX `fk_artwork_developmentSurface_idx` ON `sql10732878`.`artwork` (`development_surface` ASC) ;


-- -----------------------------------------------------
-- Table `BoteroDb`.`ArtisticStyle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql10732878`.`artistic_style` (
  `id_artistic_style` INT AUTO_INCREMENT NOT NULL,
  `style_name` VARCHAR(250) NOT NULL,
  `style_description` TEXT(2000) NOT NULL,
  PRIMARY KEY (`id_artistic_style`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BoteroDb`.`artwork_artisticStyle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql10732878`.`artwork_artisticStyle` (
  `id_artwork` INT NOT NULL,
  `id_artistic_style` INT NOT NULL,
  PRIMARY KEY (`id_artistic_style`, `id_artwork`),
  CONSTRAINT `fk_artwork_style`
    FOREIGN KEY (`id_artwork`)
    REFERENCES `sql10732878`.`artwork` (`id_artwork`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_style_artwork`
    FOREIGN KEY (`id_artistic_style`)
    REFERENCES `sql10732878`.`artistic_style` (`id_artistic_style`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_artwork_style_idx` ON `sql10732878`.`artwork_artisticStyle` (`id_artwork` ASC) ;

CREATE INDEX `fk_style_artwork_idx` ON `sql10732878`.`artwork_artisticStyle` (`id_artistic_style` ASC) ;


-- -----------------------------------------------------
-- Table `BoteroDb`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql10732878`.`status_account` (
  `id_status_account` INT AUTO_INCREMENT NOT NULL,
  `status_account` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_status_account`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BoteroDb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql10732878`.`users` (
  `id_user` INT AUTO_INCREMENT NOT NULL,
  `id_person` INT NOT NULL,
  `status_account` INT NOT NULL,
  `username` VARCHAR(15) NOT NULL,
  `password_user` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_user`),
  CONSTRAINT `fk_person_user`
    FOREIGN KEY (`id_person`)
    REFERENCES `sql10732878`.`person` (`id_person`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_status`
    FOREIGN KEY (`status_account`)
    REFERENCES `sql10732878`.`status_account` (`id_status_account`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_person_user_idx` ON `sql10732878`.`users` (`id_person` ASC) ;

CREATE UNIQUE INDEX `username_UNIQUE` ON `sql10732878`.`users` (`username` ASC) ;

CREATE INDEX `fk_user_status_idx` ON `sql10732878`.`users` (`status_account` ASC) ;


-- -----------------------------------------------------
-- Table `BoteroDb`.`provenance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql10732878`.`provenance` (
  `id_provenance` INT AUTO_INCREMENT NOT NULL,
  `city` VARCHAR(100) NOT NULL,
  `start_date_of_possession` DATE NOT NULL,
  `end_date_of_possession` DATE NOT NULL,
  `legal_status` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`Id_provenance`))
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `BoteroDb`.`obra_procedencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql10732878`.`artwork_provenance` (
  `id_artwork` INT NOT NULL,
  `id_provenance` INT NOT NULL,
  PRIMARY KEY (`id_provenance`, `id_artwork`),
  CONSTRAINT `fk_artwork_provenance`
    FOREIGN KEY (`id_artwork`)
    REFERENCES `sql10732878`.`artwork` (`id_artwork`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_provenance_artwork`
    FOREIGN KEY (`id_provenance`)
    REFERENCES `sql10732878`.`provenance` (`id_provenance`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_artwork_provenance_idx` ON `sql10732878`.`artwork_provenance` (`id_artwork` ASC) ;

CREATE INDEX `fk_provenance_artwork_idx` ON `sql10732878`.`artwork_provenance` (`id_provenance` ASC) ;


-- -----------------------------------------------------
-- Table `BoteroDb`.`materials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql10732878`.`materials` (
  `id_material` INT NOT NULL AUTO_INCREMENT,
  `material_name` VARCHAR(250) NOT NULL,
  `material_description` TEXT(2000) NOT NULL,
  PRIMARY KEY (`id_material`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BoteroDb`.`devSurf_materials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql10732878`.`devSurf_materials` (
  `id_surface` INT NOT NULL,
  `id_material` INT NOT NULL,
  PRIMARY KEY (`id_material`, `id_surface`),
  CONSTRAINT `fk_surface_material`
    FOREIGN KEY (`id_surface`)
    REFERENCES `sql10732878`.`development_surface` (`id_development`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_materials_surface`
    FOREIGN KEY (`id_material`)
    REFERENCES `sql10732878`.`materials` (`id_material`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_surface_material_idx` ON `sql10732878`.`devSurf_materials` (`id_surface` ASC) ;

CREATE INDEX `fk_materials_surface_idx` ON `sql10732878`.`devSurf_materials` (`id_material` ASC) ;


-- -----------------------------------------------------
-- Table `BoteroDb`.`artwork_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql10732878`.`artwork_user` (
  `id_artwork` INT NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id_artwork`, `id_user`),
  CONSTRAINT `fk_artwork_user`
    FOREIGN KEY (`id_artwork`)
    REFERENCES `sql10732878`.`artwork` (`id_artwork`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_artwork`
    FOREIGN KEY (`id_user`)
    REFERENCES `sql10732878`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_artwork_user_idx` ON `sql10732878`.`artwork_user` (`id_artwork` ASC) ;

CREATE INDEX `fk_user_artwork_idx` ON `sql10732878`.`artwork_user` (`id_user` ASC) ;


-- -----------------------------------------------------
-- Table `BoteroDb`.`metadata`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql10732878`.`metadata` (
  `id_metadata` INT AUTO_INCREMENT NOT NULL,
  `id_artwork` INT NOT NULL,
  `first_name` VARCHAR(250) NOT NULL,
  `last_name` VARCHAR(250) NOT NULL,
  `capture_date` DATE NOT NULL,
  `capturing_device` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_metadata`),
  CONSTRAINT `fk_artwork_metadata`
    FOREIGN KEY (`id_artwork`)
    REFERENCES `sql10732878`.`artwork` (`id_artwork`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_artwork_metadata_idx` ON `sql10732878`.`metadata` (`id_artwork` ASC) ;


-- -----------------------------------------------------
-- Table `BoteroDb`.`Comment`
-- -----------------------------------------------------
DROP TABLE `sql10732878`.`comment_user`;
CREATE TABLE IF NOT EXISTS `sql10732878`.`comment_user` (
  `id_comment` INT AUTO_INCREMENT NOT NULL,
  `id_artwork` INT NOT NULL,
  `id_user` INT NOT NULL,
  `commentary` TEXT(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `commentary_date` DATE NOT NULL,
  PRIMARY KEY (`id_comment`),
  CONSTRAINT `fk_id_artwork_comment`
    FOREIGN KEY (`id_artwork`)
    REFERENCES `sql10732878`.`artwork` (`id_artwork`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_comment`
    FOREIGN KEY (`id_user`)
    REFERENCES `sql10732878`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_id_artwork_comment_idx` ON `sql10732878`.`comment_user` (`id_artwork` ASC) ;

CREATE INDEX `fk_user_comment_idx` ON `sql10732878`.`comment_user` (`id_user` ASC) ;


-- -----------------------------------------------------
-- Table `BoteroDb`.`link_picture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql10732878`.`link_picture` (
  `id_link_picture` INT AUTO_INCREMENT NOT NULL,
  `id_metadata` INT NOT NULL,
  `link_picture` VARCHAR(150) NULL,
  PRIMARY KEY (`id_link_picture`),
  CONSTRAINT `fk_metadata_link_picture`
    FOREIGN KEY (`id_metadata`)
    REFERENCES `sql10732878`.`metadata` (`id_metadata`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_metadata_link_picture_idx` ON `sql10732878`.`link_picture` (`id_metadata` ASC) ;


-- -----------------------------------------------------
-- Table `BoteroDb`.`social_calification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql10732878`.`social_calification` (
  `id_social_calification` INT AUTO_INCREMENT NOT NULL,
  `id_artwork` INT NOT NULL,
  `amount_likes` INT NULL,
  `amount_dislikes` INT NULL,
  `star_points` INT NULL,
  PRIMARY KEY (`id_social_calification`),
  CONSTRAINT `fk_artwork_social_calification`
    FOREIGN KEY (`id_artwork`)
    REFERENCES `sql10732878`.`artwork` (`id_artwork`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_artwork_social_calification_idx` ON `sql10732878`.`social_calification` (`id_artwork` ASC) ;


-- -----------------------------------------------------
-- Table `BoteroDb`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql10732878`.`rol` (
  `id_rol` INT AUTO_INCREMENT NOT NULL,
  `rol_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BoteroDb`.`users_rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql10732878`.`users_rol` (
  `id_users_rol` INT NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id_users_rol`, `id_user`),
  CONSTRAINT `fk_users_rol_user`
    FOREIGN KEY (`id_users_rol`)
    REFERENCES `sql10732878`.`rol` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_users_rol`
    FOREIGN KEY (`id_user`)
    REFERENCES `sql10732878`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_users_rol_user_idx` ON `sql10732878`.`users_rol` (`id_users_rol` ASC) ;
CREATE INDEX `fk_user_users_rol_idx` ON `sql10732878`.`users_rol` (`id_user` ASC) ;


-- -----------------------------------------------------
-- Table `BoteroDb`.`artist_person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql10732878`.`artist_person` (
  `id_artwork` INT NOT NULL,
  `id_person` INT NOT NULL,
  PRIMARY KEY (`id_artwork`, `id_person`),
  CONSTRAINT `fk_artwork_person`
    FOREIGN KEY (`id_artwork`)
    REFERENCES `sql10732878`.`artwork` (`id_artwork`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_person_artwork`
    FOREIGN KEY (`id_person`)
    REFERENCES `sql10732878`.`person` (`id_person`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_artwork_person_idx` ON `sql10732878`.`artist_person` (`id_artwork` ASC) ;

CREATE INDEX `fk_person_artwork_idx` ON `sql10732878`.`artist_person` (`id_person` ASC) ;


-- -----------------------------------------------------
-- Table `BoteroDb`.`module`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql10732878`.`module` (
  `id_module` INT AUTO_INCREMENT NOT NULL,
  `module_name` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id_module`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BoteroDb`.`operation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql10732878`.`operation` (
  `id_operation` INT AUTO_INCREMENT NOT NULL,
  `operation_name` VARCHAR(150) NOT NULL,
  `id_module` INT NOT NULL,
  PRIMARY KEY (`id_operation`),
  CONSTRAINT `fk_module_operations`
    FOREIGN KEY (`id_module`)
    REFERENCES `sql10732878`.`module` (`id_module`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_module_operations_idx` ON `sql10732878`.`operation` (`id_module` ASC) ;


-- -----------------------------------------------------
-- Table `BoteroDb`.`rol_operation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql10732878`.`rol_operation` (
  `id_rol` INT NOT NULL,
  `id_operation` INT NOT NULL,
  PRIMARY KEY (`id_rol`, `id_operation`),
  CONSTRAINT `fk_rol_operation`
    FOREIGN KEY (`id_rol`)
    REFERENCES `sql10732878`.`rol` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_operacion_rol`
    FOREIGN KEY (`id_operation`)
    REFERENCES `sql10732878`.`operation` (`id_operation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_rol_operation_idx` ON `sql10732878`.`rol_operation` (`id_rol` ASC) ;

CREATE INDEX `fk_operacion_rol_idx` ON `sql10732878`.`rol_operation` (`id_operation` ASC) ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
